products = [
    "Enchanted Crystal Forest",
    "Mystical Aurora Skyscraper",
    "Wizard's Potion Laboratory",
    "Magical Cybernetic Animals",
    "Ethereal Dreamcatcher Office",
    "Moonlit Dragon Boardroom",
    "Whimsical Cloud Cityscape",
    "Spellbinding Constellation Network",
    "Celestial Corporate Garden",
    "Astral Projection Workspace",
    "Elixir of Innovation Studio",
    "Charmed Quantum Computer",
    "Sorcerer's Data Center",
    "Majestic Unicorn Start-up",
    "Fairy-tale Virtual Reality",
    "Mythical Phoenix Incubator",
    "Arcane Holographic Interface",
    "Supernatural Machine Learning",
    "Mystic Algorithmic Cauldron",
    "Enchanted Tech Tree"
]

essentials = [
    "Responsive Web Design",
    "User Interface Elements",
    "Coding and Programming Languages",
    "Search Engine Optimization",
    "Web Security and Privacy",
    "Website Analytics Dashboard",
    "Mobile App Development",
    "Social Media Integration",
    "E-commerce Shopping Cart",
    "Content Management System",
    "Website Hosting and Domain",
    "Web Development Team",
    "Multimedia Integration",
    "User Experience Design",
    "Accessibility and Inclusivity",
    "Email Marketing Campaign",
    "Website Wireframe",
    "Online Collaboration Tools",
    "Customer Support Services",
    "Website Page Speed Optimization",
    "Browser Compatibility Testing",
    "Website Update and Maintenance",
    "Online Advertising and Promotion",
    "Landing Page Optimization",
    "Conversion Rate Optimization",
    "Website Typography and Fonts",
    "Web Development Project Planning",
    "Web Design Color Theory",
    "Web Development Best Practices",
    "Online Portfolio and Resume"
]


professionalImages = [
    "Sleek Modern Office Space",
    "Elegant Business Meeting",
    "Cutting-Edge Technology Showcase",
    "Dynamic Team Collaboration",
    "Innovative Product Presentation",
    "Efficient Workspace Organization",
    "Powerful Corporate Branding",
    "Diverse Professional Networking",
    "Strategic Planning Session",
    "Influential Leadership Conference",
    "Expert Technical Support",
    "Global Supply Chain Management",
    "High-Performance Data Center",
    "Sophisticated Financial Analysis",
    "State-of-the-Art Medical Facility",
    "Inspiring Architectural Design",
    "Advanced Manufacturing Process",
    "Clean Renewable Energy Solutions",
    "Futuristic Urban Transportation",
    "Progressive Sustainable Development"
]


constructionImages = [
    "Panoramic Cityscape Construction",
    "Modern Skyscraper Framework",
    "Innovative Green Building Design",
    "Dynamic Bridge Engineering",
    "Majestic Tower Crane in Action",
    "Sunset Over Construction Site",
    "Busy Urban Infrastructure Development",
    "Aerial View of Expansive Project",
    "Eco-friendly Residential Complex",
    "Futuristic Commercial Architecture",
    "Historic Renovation and Preservation",
    "Industrial Construction Equipment",
    "Efficient Modular Construction",
    "Stunning Interior Fit-Out Progress",
    "Safe and Organized Worksite",
    "Powerful Earthmoving Machinery",
    "Concrete Jungle Transformation",
    "Harmonious Public Space Development",
    "Skyline Changing High-rise",
    "Detailed Blueprint and Model"
]

yogaParallax = [
    "Sunrise Yoga Flow",
    "Tranquil Zen Garden",
    "Harmonious Lotus Pond",
    "Mountain Serenity Retreat",
    "Tropical Beach Meditation",
    "Elegant Bamboo Studio",
    "Peaceful Forest Sanctuary",
    "Candlelit Mindfulness Space",
    "Graceful Yoga Silhouettes",
    "Vibrant Chakra Alignment",
    "Soothing Aerial Yoga",
    "Majestic Waterfall Sanctuary",
    "Starry Night Yoga Session",
    "Sacred Geometry Studio",
    "Mind-Body Balance Bridge",
    "Spiritual Desert Oasis",
    "Blossoming Yoga Garden",
    "Floating Yoga Pavilion",
    "Yoga among the Clouds",
    "Energy Flow Labyrinth"
]


cult = [
"Divine Nature Temple ",
"Cosmic Energy Center ",
"Sacred Fire Ceremony",
"Mystic Moonlit Forest",
"Enchanted Crystal Cave",
"Celestial Sky Meditation",
"Elemental Earth Ritual",
"Angelic Chanting Circle",
"Serene Waterfall Sanctuary",
"Ancient Wisdom Library",
"Awakening Sunrise Celebration",
"Celestial Alignment Ceremony",
"Sacred Sound Healing Circle",
"Elemental Magic Garden",
"Lunar Eclipse Gathering",
"Pristine Mountain Peak Meditation",
"Oceanic Dream Retreat",
"Mystic Pyramid Sanctuary",
"Golden Sunset Yoga Session",
"Shamanic Medicine Wheel Ceremony"
]

